# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 18:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_sku', models.CharField(max_length=50)),
                ('product_type', models.CharField(max_length=2)),
                ('desc', models.CharField(max_length=200)),
                ('product_generation', models.IntegerField(default=0)),
                ('is_pack', models.IntegerField(default=0)),
                ('bundle', models.IntegerField(default=0)),
                ('collection', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ProductsBundle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protection', models.CharField(max_length=50)),
                ('comment', models.CharField(max_length=50)),
                ('bundler_product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productsbundle_bundler_product_id', to='products.Product')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productsbundle_product_id', to='products.Product')),
            ],
        ),
    ]
