# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 18:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productsbundle',
            old_name='bundler_product_id',
            new_name='bundler_product',
        ),
        migrations.RenameField(
            model_name='productsbundle',
            old_name='product_id',
            new_name='product',
        ),
    ]
